### ISSUE TITLE
in data field new field are not able to add like gstin number or contact number, also if the keys are different than the templets then it disturbed the pdf output

### ISSUE THREAD

**Issue by ramanabhinav7** [dveldhoen/easyinvoice-nodejs-demo#1]
![image](https://github.com/dveldhoen/easyinvoice-nodejs-demo/assets/82759038/5af2c295-b1c7-4d07-acb1-b0979f359b96)

**Comment by dveldhoen** [comment]
Sorry, I don't really understand your issue. Could you be a bit more specific?

**Comment by dveldhoen** [comment]
No response, so closing the ticket for now.

**Comment by ramanabhinav7** [comment]
sorry @dveldhoen for being late, by the way i used pdf kit on that time, because easy invoice was fast but i wanted more modifications.
Thankyou for your response.

**Comment by dveldhoen** [comment]
No problem! Thanks for your response. Good luck.
